- name: Setup working environment
  hosts: localhost
  vars:
    vars_files:
      - vars/main.yml

  tasks:
    - name: Create tmp dir
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: "0755"

    - name: Configure git
      ansible.builtin.include_tasks: tasks/git.yml

    - name: Install packages
      ansible.builtin.include_tasks: tasks/packages.yml

    - name: Install terraform tools
      ansible.builtin.include_tasks: tasks/terraform.yml

    - name: Configure vscode
      ansible.builtin.include_tasks: tasks/vscode.yml

    - name: Config changes
      ansible.builtin.include_tasks: tasks/config.yml

    - name: Cleanup tmp dir
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: absent
      become: true

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: handlers/main.yml
