- name: Setup working environment
  hosts: localhost
  vars:
    setup_open_ssh_server: false
    tmp_dir: /tmp/ansible
    username: "{{ lookup ('env', 'USER') }}"
    home_dir: "{{ lookup ('env', 'HOME') }}"
    minikube_version: 1.22.0-0
    vagrant_version: 2.2.10
    vscode_settings: "{{ home_dir }}/.config/Code/User/settings.json"
    terraform:
      version: 1.7.2
      env:
        version: 3.0.0
        folder: "{{ home_dir }}/.tfenv"
      github: https://github.com/terraform
      docs:
        version: 0.17.0
      lint:
        version: 0.50.3
    git:
      email: x
      username: x
    repos:
      - package:
          name: helm
          repository:
            helm: deb https://baltocdn.com/helm/stable/debian/ all main
          public_keys:
            - https://baltocdn.com/helm/signing.asc
      - package:
          name: opera-stable
          repository:
            opera-stable: deb [arch=i386,amd64] https://deb.opera.com/opera-stable/ stable non-free
          public_keys:
            - https://deb.opera.com/archive.key
      - package:
          name: code
          repository:
            vscode: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
          public_keys:
            - https://packages.microsoft.com/keys/microsoft.asc

  tasks:
    - name: Create tmp dir
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: "0755"

    - name: Configure git
      ansible.builtin.include_tasks: tasks/git.yml

    - name: Install packages
      ansible.builtin.include_tasks: tasks/packages.yml

    - name: Install terraform tools
      ansible.builtin.include_tasks: tasks/terraform.yml

    - name: Configure vscode
      ansible.builtin.include_tasks: tasks/vscode.yml

    - name: Config changes
      ansible.builtin.include_tasks: tasks/config.yml

    - name: Cleanup tmp dir
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: absent
      become: true

  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml
