- name: Setup working environment
  hosts: localhost
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Create tmp dir
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: "0755"

  tasks:
    - name: Configure git
      ansible.builtin.include_tasks: tasks/git.yml
      tags: git

    - name: Install packages
      ansible.builtin.include_tasks: tasks/packages.yml
      tags: packages

    - name: Install terraform tools
      ansible.builtin.include_tasks: tasks/terraform.yml
      tags: terraform

    - name: Configure vscode
      ansible.builtin.include_tasks: tasks/vscode.yml
      tags: vscode

    - name: Config changes
      ansible.builtin.include_tasks: tasks/config.yml
      tags: config

  post_tasks:
    - name: Cleanup tmp dir
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: absent
      become: true

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: handlers/main.yml
