- name: Add git email
  community.general.git_config:
    name: user.email
    scope: system
    value: "{{ git.email }}"
  become: true
  when:
    - '"@" in git.email'

- name: Add git user name
  community.general.git_config:
    name: user.name
    scope: system
    value: "{{ git.username }}"
  become: true
  when:
    - 'git.username | length > 1'

- name: Set vim as default editor for git
  community.general.git_config:
    name: user.editor
    scope: system
    value: vim
  become: true
