- name: Enable and restart sshd
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: restarted
  become: true

- name: Restart docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: restarted
  become: true

# This is to make sure that minikube can be started after playbook finishes without pulling images
- name: Start and stop minikube
  ansible.builtin.shell:
    cmd: "minikube start && minikube stop"
  changed_when: false
